apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sample-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/sojay/fluxrepo  # Replace with your repo URL
  ref:
    branch: release
  secretRef:
    name: flux-docker-auth