apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sample-app
  namespace: flux-system
spec:
  interval: 1m
  path: "./kubernetes/manifests"
  prune: true
  sourceRef:
    kind: GitRepository
    name: sample-app